//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil
//     Les modifications apportées à ce fichier seront perdues si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;

namespace Domain
{

    public class Course
    {


        public Course()
        {

        }

        public Course(string lieu, double distance, string description, DateTime date)
        {
            this.Lieu = lieu;
            this.Distance = distance;
            this.Description = description;
            this.Date = date;
        }

        public virtual string Lieu
        {
            get;
            set;
        }

        public virtual int Id
        {
            get;
            set;
        }

        public virtual DateTime Date
        {
            get;
            set;
        }

        public virtual string Description
        {
            get;
            set;
        }

        public virtual double Distance
        {
            get;
            set;
        }

        public virtual List<Resultat> LesResultats
        {
            get;
            set;
        }

    }

}