//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil
//     Les modifications apportées à ce fichier seront perdues si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Domain;

namespace Domain
{

    public class Resultat
    {

        public Resultat() { }

        public Resultat(Course course, Coureur coureur)
        {
            this.LeCoureur = coureur;
            this.LaCourse = course;
            this.AllureMoyenne = 0;
            this.NumDossard = 0;
            this.VitesseMoyenne = 0;            
            this.Temps= new TimeSpan(0, 0, 0);
            this.TempsEnSecondes = CalculTempsEnSeconde(this.Temps);
        }

        public virtual int NumDossard
        {
            get;
            set;
        }
        public virtual int Id
        {
            get;
            set;
        }

        public virtual TimeSpan Temps
        {
            get;
            set;
        }

        public virtual double VitesseMoyenne
        {
            get;
            set;
        }

        public virtual double AllureMoyenne
        {
            get;
            set;
        }

        public virtual Course LaCourse
        {
            get;
            set;
        }

        public virtual Coureur LeCoureur
        {
            get;
            set;
        }

        public virtual int Classement
        {
            get;
            set;
        }

        public virtual int TempsEnSecondes
        {
            get;
            set;
        }

        public virtual int CalculTempsEnSeconde(TimeSpan t)
        {
            int temps = t.Seconds + t.Minutes * 60 + t.Hours * 60 * 60;
            return temps;
        }

        public virtual double CalculAllureMoyenne(double distance)
        {
            return this.TempsEnSecondes / 60 / distance / 1000;
        }

        public virtual double CalculVitesseMoyenne(double distance)
        {
            return distance / 1000 / this.TempsEnSecondes / 60 / 60;
        }

    }
}

