//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil
//     Les modifications apportées à ce fichier seront perdues si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Domain;

namespace Domain
{

    public class Resultat
    {
        public virtual int Id
        {
            get;
            set;
        }

        public virtual TimeSpan Temps
        {
            get;
            set;
        }

        public virtual double VitesseMoyenne
        {
            get;
            set;
        }

        public virtual double AllureMoyenne
        {
            get;
            set;
        }

        public virtual Course LaCourse
        {
            get;
            set;
        }

        public virtual Participant LeParticipant
        {
            get;
            set;
        }

    }
}

