//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil
//     Les modifications apportées à ce fichier seront perdues si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Course
{

    public Course()
    {

    }

    public Course(string lieu, double distance, string description, DateTime date)
    {
        this.Lieu = lieu;
        this.Distance = distance;
        this.Description = description;
        this.Date = date;
    }

	private string Lieu
	{
		get;
		set;
	}

	private int Id
	{
		get;
		set;
	}

	private DateTime Date
	{
		get;
		set;
	}

	private string Description
	{
		get;
		set;
	}

	private double Distance
	{
		get;
		set;
	}

	public virtual List<Resultat> LesResultats
	{
		get;
		set;
	}

}

