//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil
//     Les modifications apportées à ce fichier seront perdues si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Course
{
	private string lieu
	{
		get;
		set;
	}

	private int id
	{
		get;
		set;
	}

	private DateTime date
	{
		get;
		set;
	}

	private string description
	{
		get;
		set;
	}

	private double distance
	{
		get;
		set;
	}

	public virtual IEnumerable<Resultat> lesResultats
	{
		get;
		set;
	}

}

