//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil
//     Les modifications apportées à ce fichier seront perdues si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Participant
{
	private int numLicence
	{
		get;
		set;
	}

	private DateTime dateDeNaissance
	{
		get;
		set;
	}

	private string prenom
	{
		get;
		set;
	}

	private string nom
	{
		get;
		set;
	}

	private string sexe
	{
		get;
		set;
	}

	private string courriel
	{
		get;
		set;
	}

	public virtual List<Sponsor> Sponsor
	{
		get;
		set;
	}

	public virtual List<Resultat> Resultat
	{
		get;
		set;
	}

}

