//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil
//     Les modifications apportées à ce fichier seront perdues si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Sponsor
{
	private string nom
	{
		get;
		set;
	}

	private int id
	{
		get;
		set;
	}

	public virtual List<Participant> Participant
	{
		get;
		set;
	}

}

